repos:
  - repo: local
    hooks:
      - id: terraform_validate_local
        name: Terraform Validate
        entry: ./Scripts/validate_terraform.sh
        language: script
        types: [terraform]
