repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: master # Point to the latest commit on the master branch
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
