repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.88.0 # The version should be the latest or the one you want to use
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
