graph LR
    SQLDB[(On-prem SQL Server Database)] --> |A new Row| ADF(ADF)
    ADF --> |Ingestion| ADLS[Azure Data Lake Gen2]
    ADLS --> |Bronze Layer| Databricks[Azure Databricks]
    ADLS --> |Silver Layer| Databricks
    ADLS --> |Gold Layer| Databricks
    Databricks --> |Transformation| Synapse[Azure Synapse Analytics]
    Synapse --> |Loading| PowerBI[Power BI]
    ADF --> |Reporting| PowerBI
    subgraph Security & Governance
        AAD([Azure Active Directory])
        AKV([Azure Key Vault])
    end
    Synapse -.-> |Security & Governance| AAD
    Synapse -.-> |Security & Governance| AKV
