name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
      vnet_name:
        description: 'Virtual Network name'
        required: true
        default: 'myVnet'
      subnet_name:
        description: 'Subnet name within the Virtual Network'
        required: true
        default: 'mySubnet'
      storage_account_prefix:
        description: 'Prefix for the storage account name, ensuring uniqueness.'
        required: true
        default: 'datapipeline'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Get Runner Public IP
        run: echo "RUNNER_IP=$(curl -s https://ifconfig.me)" >> $GITHUB_ENV

      - name: Set Client IP for SQL Firewall Rule
        run: |
          echo "TF_VAR_client_ip_addresses=\"['${{ env.RUNNER_IP }}']\"" >> $GITHUB_ENV

      - name: Terraform Init with Backend
        run: |
          terraform -chdir=./Terraform init \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" \
            -backend-config="storage_account_name=${{ secrets.STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}"

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}
          TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_key_vault_name: ${{ secrets.KEY_VAULT_NAME }}
          TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_sql_admin_login: ${{ secrets.SQL_ADMIN_LOGIN }}
          TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
          TF_VAR_storage_account_connection_string: ${{ secrets.STORAGE_ACCOUNT_CONNECTION_STRING }}
          TF_VAR_storage_account_prefix: ${{ github.event.inputs.storage_account_prefix }}
          TF_VAR_environment: ${{ github.event.inputs.environment }}
          TF_VAR_vnet_name: ${{ github.event.inputs.vnet_name }}
          TF_VAR_subnet_name: ${{ github.event.inputs.subnet_name }}
          TF_VAR_vnet_address_space: '["10.0.0.0/16"]'
          TF_VAR_subnet_address_prefixes: '["10.0.1.0/24"]'

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}
          TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_key_vault_name: ${{ secrets.KEY_VAULT_NAME }}
          TF_VAR_tenant_id: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_sql_admin_login: ${{ secrets.SQL_ADMIN_LOGIN }}
          TF_VAR_sql_admin_password: ${{ secrets.SQL_ADMIN_PASSWORD }}
          TF_VAR_storage_account_connection_string: ${{ secrets.STORAGE_ACCOUNT_CONNECTION_STRING }}
          TF_VAR_storage_account_prefix: ${{ github.event.inputs.storage_account_prefix }}
          TF_VAR_environment: ${{ github.event.inputs.environment }}
          TF_VAR_vnet_name: ${{ github.event.inputs.vnet_name }}
          TF_VAR_subnet_name: ${{ github.event.inputs.subnet_name }}
          TF_VAR_vnet_address_space: '["10.0.0.0/16"]'
          TF_VAR_subnet_address_prefixes: '["10.0.1.0/24"]'
