name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - 'Terraform/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./Terraform

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Terraform Plan
        run: terraform plan -var 'arm_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}' -var 'arm_tenant_id=${{ secrets.ARM_TENANT_ID }}' -var 'arm_client_id=${{ secrets.ARM_CLIENT_ID }}' -var 'arm_client_secret=${{ secrets.ARM_CLIENT_SECRET }}' -var 'resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}' -var 'location=${{ secrets.LOCATION }}'
        working-directory: ./Terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var 'arm_subscription_id=${{ secrets.ARM_SUBSCRIPTION_ID }}' -var 'arm_tenant_id=${{ secrets.ARM_TENANT_ID }}' -var 'arm_client_id=${{ secrets.ARM_CLIENT_ID }}' -var 'arm_client_secret=${{ secrets.ARM_CLIENT_SECRET }}' -var 'resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}' -var 'location=${{ secrets.LOCATION }}'
        working-directory: ./Terraform
