name: Terraform Import Resource Group and Setup Variables

on:
  workflow_dispatch:
    inputs:
      storage_account_name:
        description: 'Storage Account Name'
        required: true

jobs:
  import-resource-group:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Azure authentication for Terraform
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_ACCESS_KEY=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      # Review Terraform State Before Import
      - name: Review Terraform State Before Import
        run: terraform state list
        working-directory: ./Terraform

      - name: Import Resource Group
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/${{ secrets.RESOURCE_GROUP_NAME }}
        working-directory: ./Terraform
        env:
          TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}
          TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_storage_account_name: ${{ github.event.inputs.storage_account_name }}

      # Review Terraform State After Import
      - name: Review Terraform State After Import
        run: |
          terraform state list
          terraform state show azurerm_resource_group.rg
        working-directory: ./Terraform
