name: Terraform Import Resource Group and Setup Variables

on:
  workflow_dispatch:
    inputs:
      subscription_id:
        description: 'Azure Subscription ID'
        required: true
      resource_group_name:
        description: 'Azure Resource Group Name to Import'
        required: true
      container_name: # Assuming you want to add this for some reason
        description: 'Azure Storage Container Name'
        required: false # Set to true if it's always required

jobs:
  import-resource-group:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Configure Azure Credentials and Variables
        run: |
          echo "ARM_CLIENT_ID=${{ secrets.ARM_CLIENT_ID }}" >> $GITHUB_ENV
          echo "ARM_CLIENT_SECRET=${{ secrets.ARM_CLIENT_SECRET }}" >> $GITHUB_ENV
          echo "ARM_SUBSCRIPTION_ID=${{ secrets.ARM_SUBSCRIPTION_ID }}" >> $GITHUB_ENV
          echo "ARM_TENANT_ID=${{ secrets.ARM_TENANT_ID }}" >> $GITHUB_ENV
          echo "ARM_ACCESS_KEY=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}" >> $GITHUB_ENV
          # If container_name is to be used later in Terraform
          if [ -n "${{ github.event.inputs.container_name }}" ]; then
            echo "TF_VAR_container_name=${{ github.event.inputs.container_name }}" >> $GITHUB_ENV
          fi

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform

      - name: Import Resource Group
        run: terraform import azurerm_resource_group.rg /subscriptions/${{ github.event.inputs.subscription_id }}/resourceGroups/${{ github.event.inputs.resource_group_name }}
        working-directory: ./Terraform
