name: Teardown Infrastructure

on:
  workflow_dispatch:
    inputs:
      storage_account_name:
        description: 'Storage Account Name'
        required: true
      # Add other inputs as needed

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      - name: Terraform Initialize
        run: terraform init
        working-directory: ./Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_storage_account_name: ${{ github.event.inputs.storage_account_name }}
          TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./Terraform
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_storage_account_name: ${{ github.event.inputs.storage_account_name }}
          TF_VAR_container_name: ${{ secrets.CONTAINER_NAME }}
          TF_VAR_location: ${{ secrets.LOCATION }}
          TF_VAR_resource_group_name: ${{ secrets.RESOURCE_GROUP_NAME }}
