name: Update Backend Configuration

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Resource Group Name'
        required: true
      storage_account_name:
        description: 'Storage Account Name'
        required: true
      container_name:
        description: 'Storage Container Name'
        required: true
      access_key:
        description: 'Storage Account Access Key'
        required: true

jobs:
  update_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update backend.tf File
        run: ./Scripts/setup_backend.sh "${{ github.event.inputs.resource_group_name }}" "${{ github.event.inputs.storage_account_name }}" "${{ github.event.inputs.container_name }}" "${{ github.event.inputs.access_key }}"
        working-directory: ${{ github.workspace }}

      - name: Commit and Push backend.tf to Repository
        run: |
          git config --local user.name "mukund1985"
          git config --local user.email "mukund.pandey@gmail.com"
          git add Terraform/backend.tf
          git commit -m "Update backend.tf with Azure storage account details"
          # Corrected the push command to use GITHUB_TOKEN for authentication
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.GITHUB_TOKEN }}" push --set-upstream origin "${{ github.head_ref }}" --force
        working-directory: ${{ github.workspace }}
