name: Update Backend Configuration

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Initial Infrastructure Setup']
    types:
      - completed

jobs:
  update_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get Azure Resource Details
        run: |
          # Fetch Azure resource details from the output of the previous workflow run
          # and store them as environment variables
          echo "Fetching Azure resource details..."
          RESOURCE_GROUP_NAME=$(jq -r '.steps.setup_infrastructure.outputs.resource_group_name' ${{ github.event.workflow_run.workflow_file }})
          STORAGE_ACCOUNT_NAME=$(jq -r '.steps.setup_infrastructure.outputs.storage_account_name' ${{ github.event.workflow_run.workflow_file }})
          CONTAINER_NAME=tfstate
          ACCESS_KEY=${{ secrets.STORAGE_ACCOUNT_ACCESS_KEY }}
          echo "RESOURCE_GROUP_NAME: $RESOURCE_GROUP_NAME"
          echo "STORAGE_ACCOUNT_NAME: $STORAGE_ACCOUNT_NAME"
          echo "CONTAINER_NAME: $CONTAINER_NAME"
          echo "ACCESS_KEY: $ACCESS_KEY"

      - name: Print Current Directory
        run: |
          echo "Current directory:"
          bash -c 'cd /home/runner/work/end_to_end_data_pipeline/end_to_end_data_pipeline && ls -ltr'

      - name: Print Permissions
        run: |
          echo "Permissions for setup_backend.sh:"
          cd /home/runner/work/end_to_end_data_pipeline/end_to_end_data_pipeline/Scripts
          ls -l setup_backend.sh
          echo "Permissions for Terraform directory:"
          ls -l ../Terraform

      - name: Setup Backend
        run: |
          echo "Running setup_backend.sh script..."
          ./setup_backend.sh "${RESOURCE_GROUP_NAME}" "${STORAGE_ACCOUNT_NAME}" "${CONTAINER_NAME}" "${ACCESS_KEY}"
        working-directory: /home/runner/work/end_to_end_data_pipeline/end_to_end_data_pipeline/Scripts
