name: Update Backend Configuration

on:
  workflow_dispatch:
    inputs:
      resource_group_name:
        description: 'Azure Resource Group Name'
        required: true
      storage_account_name:
        description: 'Azure Storage Account Name'
        required: true
      access_key:
        description: 'Azure Storage Account Access Key'
        required: true

jobs:
  update_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Backend
        run: |
          echo "Setting up backend with provided details."
          ./setup_backend.sh "${{ github.event.inputs.resource_group_name }}" "${{ github.event.inputs.storage_account_name }}" "tfstate" "${{ github.event.inputs.access_key }}"
        working-directory: ./Scripts
